C07 kks dialogue
IllusionMods/KKS-Translation pull request #115
Opened 2021-10-20 21:02 UTC by scharmers

These are some c07 kks non-H dialogue translations

2021-10-20 22:24 UTC, ManlyMarco requested changes

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/1001/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/1002/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/1003/translation.txt
> +「いいじゃん。なー……あ、なんならお揃いとかでもいいぞ」=“Here's a good one. Na- ...ah, you can have a matching set, if that's what you want.”
```suggestion
//「そ、そんな言われ方したら、ますますプレッシャーだよ」=
「いいじゃん。なー……あ、なんならお揃いとかでもいいぞ」=“Here's a good one. Na- ...ah, you can have a matching set, if that's what you want.”
```
Removed line

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/1004/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/2/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/29/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/30/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/31/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/32/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/33/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/36/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/37/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/39/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/41/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/43/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/44/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/45/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/46/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/47/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/49/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/5/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/50/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/51/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/64/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/63/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/62/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/61/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/60/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/53/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/52/translation.txt
> +
```suggestion
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/48/translation.txt
> +「俺は……ソーキそばを頼もうかな」=“I think I'lll order... the sakisoba.”
```suggestion
「俺は……ソーキそばを頼もうかな」=“I think I'lll order... the soki soba.”
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/38/translation.txt
> +（……頑張ろう）=(...let's do this.”
```suggestion
（……頑張ろう）=(...let's do this.)
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/3/translation.txt
> +「俺も……[H名]のことが好きだったんだ。両想いなんだから、付き合わない理由なんてないでしょ？」=“I... like you too,[H名]. With out feelings for each other, there's no reason not to go our with you, right?”
```suggestion
「俺も……[H名]のことが好きだったんだ。両想いなんだから、付き合わない理由なんてないでしょ？」=“I... like you too, [H名]. With out feelings for each other, there's no reason not to go our with you, right?”
```

2021-10-20 22:24 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/0/translation.txt
> +「あっ、憧れぇ～？　やめろよ、ちょっと……って、確かにそうかも……な」=“Ah--, look up to me~? Come off it with that stuff... no, maybe that really might be the case... maybe.“
```suggestion
「あっ、憧れぇ～？　やめろよ、ちょっと……って、確かにそうかも……な」=“Ah--, look up to me~? Come off it with that stuff... no, maybe that really might be the case... maybe.”
```

2021-11-03 14:15 UTC, xmexvo requested changes
Mistranslation cleanups & edits

2021-11-03 14:15 UTC, xmexvo commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/32/translation.txt
> +「周りの迷惑になるって！」=“You're gonna freak out everyone around us!”
```suggestion
「ここは風が気持ちいいね」=“The breeze feels good here.”
「だな。爽やかすぎて叫びたくなってくるぜ」=“Yeah. It's so relaxing, it makes me want to scream.”
「その気持ちは分かんないんだけど……」=“I'm not sure I can relate...”
「マジで？　何かに感動したときとかさ、自分中で気持ちがぐわーって湧き上がって来たりしないのか？」=“For real? When something moves you, don't you feel a surge of emotion inside yourself?”
「まあ、感動した時に感情が込み上げることはあるけど……それをそのまま言葉にはしないかな」=“Well, sure, I get emotional when I'm moved... but I guess I usually don't put them into words?”
「そうなんだな……そういう時は自分の感情に素直になった方がいいと思うぜ。こんな風にさ……最高だぁー！！」=“Is that so... I think in best to be honest with yourself in situations like those. Like this... THIS IS THE BEST-!!”
「周りの迷惑になるって！」=“You're gonna freak out everyone around us!”
```

2021-11-03 14:15 UTC, xmexvo commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/4/translation.txt
> +「……わかった。や、ヤるか！　私の決意が鈍らないうちに始めてくれ！」=“...alright. Let's do it! We'd better start before I get cold feet!”
```suggestion
「……わかった。や、ヤるか！　私の決意が鈍らないうちに始めてくれ！」=“...alright. L-Let's do one another! We'd better start before I get cold feet!”
```

2021-11-03 14:15 UTC, xmexvo commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/36/translation.txt
> +「いや普通に遊ぼうよ」=“No, let's just play.”
```suggestion
「さぁて、二人で競えるレジャーはないかな……」=“Let's see, is there something that we can both compete in...”
「一緒に楽しむものなんだから、競争する様なものはないと思うよ」=“They're all for us to enjoy with each other, so I don't think there's going to be anything that we can compete in.”
「あったとしても、勝てる自信ないし……やめておきたいな」=“And even if there is, I'm not sure that I'd be able to win... And so I'd rather not.”
「おいおい、男のくせに情けないぞ！　よしっ、お前に気合を入れる為に稽古をするか！」=“Come on, you're so pathetic for a guy! Right!  Let's practice to get you all fired up!
「いや普通に遊ぼうよ」=“No, let's just play like normal.”
```

2021-11-03 14:15 UTC, xmexvo commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/37/translation.txt
> +「悪い悪い、どうしてもそういう風に考えちゃうんだって。よし、目的も分かったことだし、楽しむとするか！」=“Sorry, sorry, I just can't help thinking that way. Alright, I know what the purpose is, and I'm going to enjoy it!”
```suggestion
「おし、どっちが早くゴールにつくか競争だな！」=“A'right, let's see who can get to the goal faster!”
「このカヤックは二人で漕ぐものだよ。あとレースをするわけじゃないから」=“The kayak's meant to be paddled by two people. And, we're not racing.”
「ただ漕ぐだけのか？　それじゃあ、あんまり盛り上がらないと思うぞ？」=“Just paddling? Well then, it's not going to very exciting, is it?”
「マングローブを楽しむ目的があるんだよ！　思考がスポーツに寄り過ぎてるよ……」=“The point is to enjoy the mangroves! You're thinking too much like this is a sport...”
「悪い悪い、どうしてもそういう風に考えちゃうんだって。よし、目的も分かったことだし、楽しむとするか！」=“Sorry, sorry, I just can't help thinking that way. Alright, now that I know what we're doing, let's go and enjoy it!”
```

2021-11-03 14:15 UTC, xmexvo commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/38/translation.txt
> +（……頑張ろう）=(...let's do this.)
```suggestion
「はぁ、はぁ……砂浜に来てやることが、かけっこって……思っても、みなかった……」=“*Heavy panting*... we come to the beach, and all you want to do is run... I never thought...”
「おいおい、もうバテてるのか？　情けないぞー！」=“Oh, come on, you're already exhausted? You're pathetic-!”
「砂に足をとられるから……走りにくいんだよ……」=“It's hard to run... my feet keep getting caught in the sand...”
「それが目的なんだって！　ほら、もっと体力をつけるんだ！」=“That's the point! Look, you need to get stronger!”
「俺に体力をつけさせて、何の意味があるのさ……？」=“What's the point of making me build my strength up...?”
「そ、それは……あれだよ……お姫様だ……いやっ！　何でもない、何も言ってないぞ！」=“Th-that's for... you know... bridal carry... no! Nothing! I didn't say anything!”
（……頑張ろう）=(....Let's do this)
```

2021-11-04 09:32 UTC, merged