Scharmers translation 101
IllusionMods/KKS-Translation pull request #149
Opened 2022-08-07 04:46 UTC by scharmers

Fixed up and completed translations for:

\communication\info_00\topictalkcommon_00 through topictalkcommon_15\translation.txt

Deleted associated zz_machineTranslation.txt files

2022-08-07 05:42 UTC, ManlyMarco requested changes
Almost there. Some things got lost from the translation files. It looks like you are replacing translation files with cleaned up machine translation files which is creating this issue. It might be better to have both open side-by-side and fill in the translation file with cleaned translations as you go.

2022-08-07 05:42 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/communication/info_00/topictalkcommon_00/translation.txt
> -//
These comments need to stay since they are used to keep track of things.

2022-08-07 05:42 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/communication/info_00/topictalkcommon_01/translation.txt
> -「やってみたいエッチってある？」=“Are there certain types of sex you want to try?”
This line got removed.

2022-08-07 05:42 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/communication/info_00/topictalkcommon_06/translation.txt
> -「やってみたいエッチってある？」=“Are there certain types of sex you want to try?”
This line got removed.

2022-08-08 09:34 UTC, ManlyMarco approved these changes
Looks good to merge. I found one removed translation but I fixed it myself.

2022-08-08 12:05 UTC, GeBo1 approved these changes

2022-08-08 12:05 UTC, merged