c08 translation
IllusionMods/KKS-Translation pull request #195
Opened 2023-05-09 20:17 UTC by ManlyMarco

Thanks to @ScrewThisNoise for providing the translations.

2023-05-10 12:55 UTC, GeBo1 requested changes

2023-05-10 12:55 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c08/00/1000/translation.txt
> +「[H名]……」=“[H]...”
```suggestion
「[H名]……」=“[H名]...”
```

2023-05-10 12:55 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c08/00/5/translation.txt
> +「[H名]……」=“[H]...”
```suggestion
「[H名]……」=“[H名]...”
```

2023-05-10 12:55 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c08/00/1008/translation.txt
> +「[H名]……」=“[H]...”
```suggestion
「[H名]……」=“[H名]...”
```

2023-05-10 12:55 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/communication/info_31/communication_08/translation.txt
> +「？　ここは男の子は入れない所だよ？」=“? Boys can't come in here, you know?”
```suggestion
「？　ここは男の子は入れない所だよ？」=“Boys can't come in here, you know?”
```

or

```suggestion
「？　ここは男の子は入れない所だよ？」=“Huh? Boys can't come in here, you know?”
```

2023-05-10 12:55 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/communication/info_50/communication_08/translation.txt
> +「？　ここは男の子は入れない所だよ？」=“? Boys can't come in here, you know?”
Same as above....

2023-05-10 19:45 UTC, GeBo1 approved these changes

2023-05-12 07:32 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/communication/info_00/communication_23/translation.txt
> +「好きだよ、[H]。[H]はどう、かな？」=“I love you, [H]。[H]。[H]。[H]. What, about you?”
```suggestion
「好きだよ、[H]。[H]はどう、かな？」=“I love you, [H]. What about you?”
```

2023-05-12 07:32 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/communication/info_31/communication_23/translation.txt
> +「好きだよ、[H]。[H]はどう、かな？」=“I love you, [H]。[H]。[H]。[H]. What, about you?”
```suggestion
「好きだよ、[H]。[H]はどう、かな？」=“I love you, [H]. What about you?”
```

2023-05-12 07:33 UTC, merged