c07 translation
IllusionMods/KKS-Translation pull request #196
Opened 2023-05-09 20:17 UTC by ManlyMarco

Thanks to @ScrewThisNoise for providing the translations.

2023-05-10 12:33 UTC, GeBo1 requested changes
Some of these were probably better before, but it's not a big deal. the commend about the `[H]` substitutions applies across the board. They should probably all be updated to match correctly.

2023-05-10 12:33 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/0/translation.txt
> +「あはは。お前って面白い奴なんだな！」=“Ahaha. You a real interesting guy, you know that?”
Assuming this a grammar error
```suggestion
「あはは。お前って面白い奴なんだな！」=“Ahaha. You're a real interesting guy, you know that?”
```

2023-05-10 12:33 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c07/00/1002/translation.txt
> +「[H名]は卓球とか得意なんじゃない？」=“Aren't you pretty good at ping pong, [H]?”
There seem to be a lot of these than have changed, which I don't think is correct. May want to do a global check substitutions match on both sides of equals in general (if so, we can handle that after).

```suggestion
「[H名]は卓球とか得意なんじゃない？」=“Aren't you pretty good at ping pong, [H名]?”
```

2023-05-10 19:45 UTC, GeBo1 approved these changes

2023-05-12 07:31 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/communication/info_00/communication_23/translation.txt
> +「好きだよ、[H]。[H]はどう、かな？」=“I love you, [H]。[H]。[H]。[H]. What, about you?”
``` suggestion
「好きだよ、[H]。[H]はどう、かな？」=“I love you, [H]. What about you?”
```

2023-05-12 07:32 UTC, merged