c05 translation
IllusionMods/KKS-Translation pull request #228
Opened 2023-09-24 10:09 UTC by ManlyMarco

Thanks to @ScrewThisNoise for providing the translations.

2023-10-19 18:01 UTC, GeBo1 requested changes

2023-10-19 23:25 UTC, ManlyMarco commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c05/00/21/translation.txt
> +「幸せ。あなたも同じように感じてる？」=“I'm in bliss. Do you feel the same way?”
"I'm in bliss" seems common and natural to me though. On the contrary "I feel blissful" feels awkward.

2023-10-20 12:57 UTC, GeBo1 commented on Translation/en/RedirectedResources/assets/abdata/adv/scenario/c05/00/21/translation.txt
> +「幸せ。あなたも同じように感じてる？」=“I'm in bliss. Do you feel the same way?”
I asked around, and no one had heard it, but if it's a thing, then it's fine.

2023-10-20 12:58 UTC, GeBo1 approved these changes

2023-10-21 20:41 UTC, merged